language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
install:
- pip install -r requirements-dev.txt
- pip install pylint
- pip install git+git://github.com/watson-developer-cloud/python-sdk.git#egg=watson-developer-cloud
script:
- sh pylint.sh
- coverage run --source=watson_developer_cloud setup.py test
after_success: coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_c3e85137836d_key -iv $encrypted_c3e85137836d_iv
  -in .env.enc -out .env -d
